### ISSUE TITLE
Automate toil tasks that can be automated.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/support#841]
The outcome should be a list of tasks that are repetitive. We should start with low hanging tasks that are commonly enacted.

I'll aggregate suggestions in the list below: 

Edit: Updating this list below, the action item now is to complete this checklist.

Apps/repo:
- [ ] Adding new/existing cluster resources to cluster-scope app (in base), if it's new then a file is required. (https://github.com/operate-first/apps/issues/608)
    - e.g: `$./add_resource.sh clusterroles example-role moc zero` 
- [ ] Adding new/existing users to a group to an environment/cluster, this would require also encrypting this group (https://github.com/operate-first/SRE/issues/304)
    - e.g. `$./add_user "john,jane,bob" operate-first moc zero` 
- [ ] Create new ArgoCD project for an user group (covered in https://github.com/operate-first/SRE/issues/305)
- [x] Add project admin/edit/view group for a namespace (https://github.com/operate-first/SRE/issues/278)
- [x] Enable monitoring on a namespace (this involves just adding the appropriate rbac) (https://github.com/operate-first/SRE/issues/277)
- [x] Script to bump openshift `ClusterVersion` resource based on available updates (https://github.com/operate-first/apps/pull/531)

Misc:
- [ ] Encrypting resources 
    - Currently some files require encrypting resources with 4 or more secrets, personally I find this a bit tedious, we opt not to use .sops.yaml due to reasons discussed [here](https://github.com/operate-first/SRE/issues/122), but maybe we can alleviate the pain of having to add multiple keys to the `--pgp` flag in some other way. (https://github.com/operate-first/SRE/issues/306)
- [ ] Auto-link docs for a given operator in issues for operator onboarding (https://github.com/operate-first/SRE/issues/307)
- [ ] Extracting the ca.crt secret for kafka onboarding from opf-kafka namespace (https://github.com/operate-first/SRE/issues/308)

Argocd-Apps:
- [ ] Create new ArgoCD app from a given repo and path for a specific namespace+cluster (https://github.com/operate-first/SRE/issues/305#issuecomment-840108267)
